In [57]:
import kagglehub
import pandas as pd

path = kagglehub.dataset_download(
    "datascikhan/e-commerce-sales-and-customer-analytics"
)

file_path = path + "/ecommerce_sales_customer_analytics_150k.csv"

df = pd.read_csv(file_path)

df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

# Data inspection

In [58]:
# Inspecting Headers.

print(df.columns)

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='str')

In [59]:
# Inspecting the dataset info.
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 47.6 MB
None

In [60]:
# Counting the occurrences of each column name.
df.columns.value_counts()

order_id                    1
order_date                  1
order_time                  1
order_status                1
sales_channel               1
customer_id                 1
customer_name               1
customer_age                1
gender                      1
customer_segment            1
customer_type               1
customer_city               1
customer_state              1
customer_country            1
region                      1
customer_postal_code        1
payment_method              1
payment_status              1
currency                    1
shipping_method             1
warehouse                   1
delivery_days               1
estimated_delivery_days     1
delivery_status             1
return_status               1
return_reason               1
customer_rating             1
review_sentiment            1
customer_review             1
marketing_channel           1
campaign_name               1
coupon_code                 1
loyalty_points_earned       1
loyalty_points_redeemed     1
quantity                    1
gross_sales                 1
discount_amount             1
tax_amount                  1
shipping_cost               1
net_sales                   1
product_cost                1
profit                      1
profit_margin_percentage    1
customer_lifetime_value     1
is_repeat_customer          1
customer_order_count        1
Name: count, dtype: int64

In [61]:
# Number of columns in the dataset.
df.shape[1]

46

In [62]:
# Inspecting for duplicates in the dataset.
df.duplicated().sum()

np.int64(0)

In [63]:
df["sales_channel"]

0           Mobile App
1              Website
2           Mobile App
3         Social Media
4         Social Media
              ...
138111      Mobile App
138112    Social Media
138113      Mobile App
138114    Social Media
138115      Mobile App
Name: sales_channel, Length: 138116, dtype: str

In [64]:
df.value_counts(["order_status"])

order_status
Completed       113559
Returned          9462
Cancelled         8398
Pending           6697
Name: count, dtype: int64

In [65]:
df[["customer_name", "customer_age"]]

           customer_name  customer_age
0           Jasmine Ryan            55
1            Scott Chase            26
2           Marc Wheeler            69
3         Jennifer Smith            65
4           Jessica Wang            34
...                  ...           ...
138111        Donna Ruiz            41
138112    Jeremy Aguirre            40
138113  Timothy Williams            39
138114    Charles Hanson            46
138115       John Miller            28

[138116 rows x 2 columns]

In [66]:
Customer_age_df = df[["customer_age"]].agg(["median", "min", "max", "sum"])

Customer_age_df

        customer_age
median          46.0
min             18.0
max             74.0
sum        6334370.0

# Analysis
## 1. SALES & REVENUE

In [67]:
# Revenue and order volume by sales channel.
sales_by_channel =  df.groupby("sales_channel").agg(orders=("order_id", "count"),
             gross_sales=("gross_sales", "sum"),
             net_sales=("net_sales", "sum")).sort_values("net_sales", ascending=False)


sales_by_channel

               orders  gross_sales    net_sales
sales_channel
Mobile App      55318  76016864.27  70834782.53
Website         48237  66289541.38  61854736.08
Marketplace     20698  28657981.08  26696190.22
Social Media    13863  18998174.15  17748554.91

In [68]:
# Revenue by region
sales_by_region = df.groupby("region").agg(
    orders=("order_id", "count"), net_sales=("net_sales", "sum")).sort_values(
        "net_sales", ascending=False)

sales_by_region

         orders    net_sales
region
South     43990  55587994.98
Central   29627  37171107.17
West      26273  34755096.47
East      21602  27054887.88
North     16624  22565177.24

In [69]:
# Net sales trend over time.
# Frequent date.

d = df.copy()
d["order_date"] = pd.to_datetime(d["order_date"])

d.set_index("order_date").resample("ME")["net_sales"].sum()

order_date
2021-01-31    2374415.22
2021-02-28    1905413.15
2021-03-31    2753256.18
2021-04-30    2469384.78
2021-05-31    2546555.37
2021-06-30    2710208.64
2021-07-31    2894416.72
2021-08-31    3220659.48
2021-09-30    2720931.59
2021-10-31    2991778.76
2021-11-30    4234660.71
2021-12-31    4900970.07
2022-01-31    2442770.60
2022-02-28    2029412.22
2022-03-31    2682800.73
2022-04-30    2516740.73
2022-05-31    2529145.45
2022-06-30    2697622.96
2022-07-31    2765292.19
2022-08-31    2947796.56
2022-09-30    2750776.22
2022-10-31    2925151.89
2022-11-30    4405731.78
2022-12-31    4634641.29
2023-01-31    2467972.04
2023-02-28    2035382.66
2023-03-31    2700460.99
2023-04-30    2495710.76
2023-05-31    2555496.97
2023-06-30    2801712.97
2023-07-31    2715818.33
2023-08-31    3070356.42
2023-09-30    2747363.20
2023-10-31    3001350.13
2023-11-30    4261793.39
2023-12-31    4674725.88
2024-01-31    2510721.37
2024-02-29    2119755.19
2024-03-31    2752681.57
2024-04-30    2635743.36
2024-05-31    2579097.07
2024-06-30    2639763.54
2024-07-31    2833868.86
2024-08-31    2860775.42
2024-09-30    2754826.02
2024-10-31    2894022.77
2024-11-30    4352110.30
2024-12-31    4533086.81
2025-01-31    2442719.60
2025-02-28    2018064.34
2025-03-31    2790317.39
2025-04-30    2536513.26
2025-05-31    2416435.27
2025-06-30    2621595.83
2025-07-31    2844927.97
2025-08-31    2958759.35
2025-09-30    2840833.95
2025-10-31    2793772.97
2025-11-30    4270161.00
2025-12-31    4555033.50
Freq: ME, Name: net_sales, dtype: float64

## 2. PROFITABILITY

In [70]:
# Most profitable regions and channels, not just highest revenue.
profit_by_region_channel = df.groupby(["region", "sales_channel"]).agg(
        net_sales=("net_sales", "sum"),
        profit=("profit", "sum"),
        avg_margin_pct=("profit_margin_percentage", "mean")).sort_values("profit", ascending=False)

profit_by_region_channel

                         net_sales      profit  avg_margin_pct
region  sales_channel
South   Mobile App     22144301.75  9285240.34       44.167363
        Website        19254966.81  8110900.72       44.140592
Central Mobile App     15024859.32  6300948.88       44.061405
West    Mobile App     13824224.37  6230391.85       46.969271
        Website        12078703.68  5461699.70       47.124677
Central Website        13058947.63  5459314.28       44.019575
East    Mobile App     10841991.09  4488579.81       43.776124
North   Mobile App      8999406.00  4145951.34       47.987973
East    Website         9499708.56  3924719.55       43.627646
North   Website         7962409.40  3683058.76       48.255155
South   Marketplace     8542923.88  3568004.34       43.945573
        Social Media    5645802.54  2379800.77       44.067968
West    Marketplace     5156569.39  2305667.80       47.176753
Central Marketplace     5472807.89  2287408.62       43.968174
East    Marketplace     4064139.96  1665916.17       43.633702
West    Social Media    3695599.03  1649493.12       46.736282
North   Marketplace     3459749.10  1587230.23       47.996962
Central Social Media    3614492.33  1525197.06       44.109003
East    Social Media    2649048.27  1100151.41       43.788670
North   Social Media    2143612.74   986721.01       47.997646

In [71]:
# Correlation between discount amount and profit margin.
discount_impact_on_margin = df[["discount_amount", "profit_margin_percentage"]].corr().iloc[0, 1]
coupon_vs_no_coupon = (
        df.assign(used_coupon=df["coupon_code"].notna())
        .groupby("used_coupon")["profit_margin_percentage"]
        .mean()
    )

discount_impact_on_margin

np.float64(-0.5993948410122624)

In [72]:
# Checking where the biggest cost drains are: product cost vs shipping cost.
cost_breakdown = df[["product_cost", "shipping_cost", "tax_amount", "discount_amount"]].sum()

cost_breakdown

cost_breakdown

product_cost       97910908.71
shipping_cost       3076959.27
tax_amount         16914090.41
discount_amount    32819346.82
dtype: float64

## 3. CUSTOMER BEHAVIOR & SEGMENTATION

In [75]:
# Highest-value customers by customer_lifetime_value.
top_customers_by_ltv = (
    df.drop_duplicates("customer_id")
      .sort_values("customer_lifetime_value", ascending=False)
      [["customer_id", "customer_name", "customer_lifetime_value", "customer_order_count"]]
      .head()
)

top_customers_by_ltv

,customer_id,customer_name,customer_lifetime_value,customer_order_count
30190,CUST-012869,Dylan Clark,30268.44,15
6077,CUST-002969,Tracy Mendez,30061.58,16
21304,CUST-017251,Jesus Ross,29375.34,15
6686,CUST-000802,Rodney Avila,29157.92,13
32169,CUST-012608,James Long,28172.12,13

In [ ]:
# the rate of returning customers
returning_customer_rate = df["is_repeat_customer"].mean() * 100
spend_comparison = df.groupby("is_repeat_customer")["net_sales"].mean()

returning_customer_rate

# summary of the returning customer rate
summary = pd.DataFrame({
    "Metric": [
        "Returning Customer Rate",
        "Average Net Sales"
    ],
    "Value": [
        returning_customer_rate,
        spend_comparison.mean()
    ]
}).round(2)

summary

                    Metric    Value
0  Returning Customer Rate    99.76
1        Average Net Sales  1293.11